"use strict";
/* Collects every Arabic string the interface can show, keyed by itself.
   Static pass over ui/app.html: HTML text nodes, translatable attributes, and JS string literals. */
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");
const src = fs.readFileSync(path.join(root, "ui/app.html"), "utf8");
const AR = /[؀-ۿ]/;
const body = src.slice(src.indexOf('<div dir="rtl"'), src.indexOf("<script>"));
const js = src.slice(src.indexOf("<script>"));
const out = new Set();
const add = s => {
  s = String(s).replace(/\\n/g, "\n").replace(/\\t/g, " ").replace(/\\(.)/g, "$1");
  s = s.replace(/\s+/g, " ").trim();
  if (!s || !AR.test(s)) return;
  if (s.length > 400) return;                 // long AI prompt blocks are not interface text
  if (/\$\{|<[a-z/]/i.test(s)) return;        // template holes and markup fragments
  if (/=>|\bfunction\b|\bconst \b|\breturn\b/.test(s)) return; // stray code from a greedy match
  out.add(s);
};
// HTML text nodes (skip inline svg artwork)
body.replace(/<svg[\s\S]*?<\/svg>/g, " ").replace(/>([^<>]+)</g, (_, x) => (add(x), ""));
// translatable attributes
const attrRe = /(?:placeholder|title|aria-label|alt|data-hint)="([^"]+)"/g;
for (let m; (m = attrRe.exec(body)); ) add(m[1]);
// JS literals. The model prompts are backtick templates containing ${…}, so the last
// pattern skips them, and anything else overlong is dropped by add().
// SUGG holds sample questions already written in several languages on purpose — leave them alone
const jsSrc = js.replace(/^const SUGG = \[.*$/m, "");
for (const re of [/"((?:[^"\\\n]|\\.)*)"/g, /'((?:[^'\\\n]|\\.)*)'/g, /`([^`\\$]*)`/g]) {
  for (let m; (m = re.exec(jsSrc)); ) add(m[1]);
}
// the requirements base is shown in the interface too: activities, checklist items, photo slots, districts
const KB = require("../public/kb.js");
Object.values(KB.ACTS).forEach(a => { add(a.name); a.items.forEach(i => add(i.t)); });
KB.SLOTS.forEach(s => { add(s.name); add(s.hint); });
KB.DISTRICTS.forEach(add);
KB.ROADMAP.forEach(add);
add(KB.NOPHOTO.ar);
add(KB.NOPHOTO_FIX.ar);
add(KB.SRC);

const keys = [...out].sort((a, b) => a.localeCompare(b, "ar"));
fs.writeFileSync(path.join(root, "tools/i18n-keys.json"), JSON.stringify(keys, null, 1) + "\n");
console.log(keys.length, "strings,", keys.reduce((n, s) => n + s.length, 0), "chars");

// public/i18n.js — the key list plus the dictionaries that ship with the app
const enPath = path.join(root, "tools/i18n-en.json");
const en = fs.existsSync(enPath) ? JSON.parse(fs.readFileSync(enPath, "utf8")) : {};
const missing = keys.filter(k => !(k in en));
const extra = Object.keys(en).filter(k => !out.has(k));
if (missing.length) console.warn("English is missing " + missing.length + " strings:\n  " + missing.join("\n  "));
if (extra.length) console.warn("English has " + extra.length + " strings no longer in the interface:\n  " + extra.join("\n  "));
const dictEn = {};
keys.forEach(k => { if (en[k]) dictEn[k] = en[k]; });
const file = `/*
 * Muyassir interface strings — generated by tools/extract-i18n.js, do not edit by hand.
 * Every visible string is keyed by its Arabic original. English ships with the app;
 * the other languages are translated on demand by /api/i18n and cached.
 */
(function (root) {
  "use strict";
  const KEYS = ${JSON.stringify(keys, null, 2)};
  const DICT = { en: ${JSON.stringify(dictEn, null, 2)} };
  const I18N = { KEYS: KEYS, dict: DICT };
  if (typeof module !== "undefined" && module.exports) module.exports = I18N;
  else root.MUYASSIR_I18N = I18N;
})(typeof window !== "undefined" ? window : globalThis);
`;
fs.writeFileSync(path.join(root, "public/i18n.js"), file);
console.log("public/i18n.js", file.length, "bytes | built-in:", Object.keys(dictEn).length, "English strings");
